### ISSUE TITLE
requestCode SIGSEGV

### ISSUE THREAD

**Issue by microo8** [signal-golang/textsecure#51]
I've just downloaded libzkgroup_linux_x86_64.so and moved it to `/usr/lib` (then `sudo ldconfig`).
Changed the phone number in `config.yml`.
Downloaded and build crayfish and run `make run` in `cmd/textsecure`

```
Found go with version go version go1.17.5 linux/amd64
LD_LIBRARY_PATH=/tmp/textsecure/cmd/textsecure go run .
INFO[2021/12/16 08:30:12] [textsecure-crayfish] Starting crayfish-backend 
DEBU[2021/12/16 08:30:12] [textsecure-crayfish-ws] BackendStartListening 
DEBU[2021/12/16 08:30:12] [textsecure-crayfish-ws] websocket connecting to crayfish-server 
DEBU[2021/12/16 08:30:12] [texsecure] register Device                  
DEBU[2021/12/16 08:30:12] [textsecure] loading config                  
INFO[2021/12/16 08:30:12] [textsecure] request verification code for  +421905118965 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x894c47]

goroutine 1 [running]:
github.com/signal-golang/textsecure.requestCode({0xc000026fb0, 0xd}, {0xc000026ff8, 0x3}, {0x0, 0xc0000001a0})
	/tmp/textsecure/server.go:125 +0x1c7
github.com/signal-golang/textsecure.registerDevice()
	/tmp/textsecure/textsecure.go:421 +0x12c
github.com/signal-golang/textsecure.Setup(0xc0000ec300)
	/tmp/textsecure/textsecure.go:297 +0x28e
main.main()
	/tmp/textsecure/cmd/textsecure/main.go:507 +0xe6
exit status 2
make: *** [Makefile:97: run] Error 1
```

**Comment by nanu-c** [comment]
This is solved now. Please try again.

**Comment by microo8** [comment]
It works now thanks.

**Comment by nanu-c** [comment]
Cool, nice to hear!
