### ISSUE TITLE
bundle of 401 during work with texsecure 

### ISSUE THREAD

**Issue by argon338** [signal-golang/textsecure#71]
When try to do anything there is 401 error

./textsecure -showdevices
INFO[0000] [textsecure] Setting log level to debug
INFO[2022/11/08 14:38:27] [textsecure-crayfish] Starting crayfish-backend 
INFO[2022/11/08 14:38:27] Registration done.                           
DEBU[2022/11/08 14:38:27] [textsecure] saving config +79636044365      
DEBU[2022/11/08 14:38:27] [textsecure] UpdateProfile ab334dad-75e5-4b1d-a210-bb522e8a332d argon 
DEBU[2022/11/08 14:38:27] [crayfish] starting crayfish e76f1cb11caad441c7961a14243d5c78fdeee2dc 
DEBU[2022/11/08 14:38:27] [crayfish] Starting libsignal-service web socket at ws://127.0.0.1:9081/libsignal 
DEBU[2022/11/08 14:38:28] [textsecure] PUT /v1/profile/ 401            
INFO[2022/11/08 14:38:28] [textsecure] Checking certificate            
INFO[2022/11/08 14:38:28] [textsecure] Using existing profile key credential 145 
DEBU[2022/11/08 14:38:28] [textsecure-crayfish-ws] BackendStartListening 
DEBU[2022/11/08 14:38:28] [textsecure-crayfish-ws] websocket connecting to crayfish-server 
DEBU[2022/11/08 14:38:28] [textsecure-crayfish-ws] websocket Connected successfully 
DEBU[2022/11/08 14:38:28] [crayfish] establishing client connection... WebSocket 
DEBU[2022/11/08 14:38:28] [textsecure] GET /v1/devices/ 401 

./textsecure  -leavegroup string      
INFO[0000] [textsecure] Setting log level to debug
INFO[2022/11/08 14:41:28] [textsecure-crayfish] Starting crayfish-backend 
INFO[2022/11/08 14:41:28] Registration done.                           
DEBU[2022/11/08 14:41:28] [textsecure] saving config +79636044365      
DEBU[2022/11/08 14:41:28] [textsecure] UpdateProfile ab334dad-75e5-4b1d-a210-bb522e8a332d argon 
DEBU[2022/11/08 14:41:28] [crayfish] starting crayfish e76f1cb11caad441c7961a14243d5c78fdeee2dc 
DEBU[2022/11/08 14:41:28] [crayfish] Starting libsignal-service web socket at ws://127.0.0.1:9081/libsignal 
DEBU[2022/11/08 14:41:28] [textsecure] PUT /v1/profile/ 401            
INFO[2022/11/08 14:41:28] [textsecure] Checking certificate            
INFO[2022/11/08 14:41:28] [textsecure] Using existing profile key credential 145 
DEBU[2022/11/08 14:41:28] [textsecure] GetRegisteredContacts           
DEBU[2022/11/08 14:41:28] [textsecure] read contacts from .config/contacts.yml 
DEBU[2022/11/08 14:41:29] [textsecure-crayfish-ws] BackendStartListening 
DEBU[2022/11/08 14:41:29] [textsecure-crayfish-ws] websocket connecting to crayfish-server 
DEBU[2022/11/08 14:41:29] [textsecure-crayfish-ws] websocket Connected successfully 
DEBU[2022/11/08 14:41:29] [crayfish] establishing client connection... WebSocket 
DEBU[2022/11/08 14:41:29] [textsecure] GET /v1/directory/auth 401      
DEBU[2022/11/08 14:41:29] [textsecure] getCredentials                  
DEBU[2022/11/08 14:41:29] [textsecure] GetAndVerifyMultiRemoteAttestation 
DEBU[2022/11/08 14:41:29] [textsecure] PUT with auth /v1/attestation/c98e00a4e3ff977a56afefe7362a27e4961e4f19e211febfbb19b897e6b80b15 401 
INFO[2022/11/08 14:41:29] Could not get contacts: could not get remote attestation invalid character 'C' looking for beginning of value

**Comment by argon338** [comment]
Adding running textsecure cli from another account to group:
[2022/11/08 14:57:44] [textsecure][groupsv2] error updating group change from serverstatus code 401

**Comment by argon338** [comment]
After I add account used for textsecure to group from mobile phone (with another account) and sent message to group textsecure panic:
>>panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x8b4bc8]

goroutine 1 [running]:
github.com/signal-golang/textsecure/groupsv2.HandleGroupsV2({0x18457291d13?, 0xaef430?}, 0xc00014ee68?)
        /home/agronovsa/dev/textsecure/groupsv2/groupsv2.go:313 +0x3e8
github.com/signal-golang/textsecure.handleDataMessage({0xc00032a600, 0x24}, {0xc00032a600, 0x24}, 0xc00013c900?, 0xc0001565a0)
        /home/agronovsa/dev/textsecure/handler.go:86 +0x1a9
github.com/signal-golang/textsecure.handleMessage({0xc00032a600, 0x24}, {0xc00032a600, 0x24}, 0xc00011af90?, {0xc0000e4e80, 0x59, 0xa0})
        /home/agronovsa/dev/textsecure/handler.go:21 +0x425
github.com/signal-golang/textsecure.handleReceivedMessage(0xc000041600)
        /home/agronovsa/dev/textsecure/textsecure.go:608 +0xd8a
github.com/signal-golang/textsecure.StartListening()
        /home/agronovsa/dev/textsecure/websocket.go:199 +0x5df
main.main()
        /home/agronovsa/dev/textsecure/cmd/textsecure/main.go:669 +0x853
